# Generated by Django 5.0.4 on 2024-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('inredients', models.TextField(verbose_name='Ingredients')),
                ('recipe', models.TextField(verbose_name='Recipe')),
                ('cooktime', models.IntegerField(verbose_name='Cooktime')),
                ('image_url', models.URLField(verbose_name='Image URL')),
            ],
        ),
    ]
