# Generated by Django 5.0.4 on 2024-04-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='inredients',
            new_name='ingredients',
        ),
    ]
