# Generated by Django 5.0.4 on 2024-04-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_rename_inredients_dishes_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dishes',
            name='images',
            field=models.FileField(blank=True, upload_to='', verbose_name='Images'),
        ),
    ]
